# -*- coding: utf-8 -*-
"""DataFrame_Displays.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dSVfD8ey3QjCkxMfYmnEAcBrpGd14n_c
"""

from google.colab import drive

drive.mount("/content/drive")

# !pip install pyspark

from pyspark import *
from pyspark.sql import DataFrame

help(DataFrame.write)

from pyspark.context import SparkContext
from pyspark.sql.session import SparkSession

sc = SparkContext("local")
spark = SparkSession(sc)

data = [
    (1, "milanlshefwegdwegd;uwed;wevdiewv", 56),
    (2, "rad;dbewiubdiuwehul", 26),
    (3, "miqhdwwgdlwgdiwegdygweydghir", 34),
    (4, "jay", 21),
]
schema = ["id", "name", "age"]
df = spark.createDataFrame(data=data, schema=schema)
df.show()

"""show()"""

df.show(truncate=False)

df.show(truncate=12)

df.show(n=2, truncate=False)

df.show(n=2, vertical=True)

"""withColumn()"""

display(df)

df.show()

from pyspark.sql.functions import col, lit

df1 = df.withColumn(colName="age", col=col("age").cast("Integer"))
df1.show()
df1.printSchema()

df2 = df1.withColumn("age", col("age") - 2)
df2.show()

df3 = df1.withColumn("new_age", col("age") - 15)
df3.show()

df3 = df3.withColumn("country", lit(("USA")))
df3.show()

"""withColumnRenamed()"""

df4 = df3.withColumnRenamed("age", "persons_age")
df4.show()
