# -*- coding: utf-8 -*-
"""PySpark_Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eCu6W02FYxhqXVOpzenqloncHIg8HN00

# **PySpark Installation**
"""

#!pip install pyspark

import pyspark

from pyspark.sql import SparkSession

"""# **DataFrame Creation**"""

spark = SparkSession.builder.appName("PySpark Example").getOrCreate()

df = spark.sql("SELECT 'Py' as low")

df.show()

spark = SparkSession.builder.getOrCreate()
df = spark.sql("""select 'PySpark' as hello """)
df.show()

from pyspark.conf import SparkConf
from pyspark.context import SparkContext

# Create a SparkConf object
conf = SparkConf().setAppName("PySpark Demo App").setMaster("local[1]")

# Get the value of 'spark.master' property
print(conf.get("spark.master"))  # Output: 'local[2]'

# Get the value of 'spark.app.name' property
print(conf.get("spark.app.name"))  # Output: 'PySpark Demo App'

spark

type(spark)

dir(spark)

help(spark.createDataFrame)

spark.createDataFrame([("Alice", 1)]).show()

spark.createDataFrame([("MARK", 52)]).show()

d = [{"name": "Alice", "age": 1}]
spark.createDataFrame(d).show()

d = [{"name": "Alice", "age": 1}]
spark.createDataFrame([("MARK", 52)]).show()

spark.createDataFrame([("Alice", 1)], ["name", "age"]).show()

from pyspark.sql import Row

Person = Row("name", "age")
df = spark.createDataFrame([Person("Alice", 1)])
df.show()

data = [(1, "mahesh"), (2, "rajesh"), (3, "suresh")]
df = spark.createDataFrame(data=data)
df.show()

data = [(1, "mahesh"), (2, "rajesh"), (3, "suresh")]
df = spark.createDataFrame(data=data, schema=["id", "name"])
df.show()
df.printSchema()

from pyspark.sql.types import *

help(StructType)

"""**Converting the datatypes**"""

data = [(1, "mahesh"), (2, "rajesh"), (3, "suresh")]
df = spark.createDataFrame(data=data, schema=["id", "name"])
schema = StructType(
    [
        StructField(name="id", dataType=IntegerType()),
        StructField(name="name", dataType=StringType()),
    ]
)
df.show()
df.printSchema()
