# -*- coding: utf-8 -*-
"""json_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AV69REkWGQ4zpy0whNbT1iHx99xwcRg-
"""

import pandas as pd

df = pd.read_json("/content/drive/MyDrive/data_practices/pandas/data/umang.json")

# print(df.to_string())

columns = list(df.iloc[0].keys())

# Create a DataFrame with the extracted column names
df = pd.DataFrame(df.values[1:], columns=columns)

# Display the DataFrame
print(df)

print(df.to_string())

df1 = pd.DataFrame(df)
df1["products"] = df1["products"].apply(
    lambda x: {"id": x["id"], "images": x["images"]}
)
print(df1)

df2 = df1.drop(columns=["total", "skip", "limit"])
print(df2)

df2.to_json("umang_edited.json", orient="records")

import pandas as pd
import json

# Read the JSON file into a Python object
with open("/content/drive/MyDrive/data_practices/pandas/data/umang.json") as f:
    json_data = json.load(f)

# Extract the column names from the first row of the JSON object
columns = list(json_data[0].keys())

# Read the JSON object into a DataFrame with the extracted column names
df = pd.DataFrame(json_data, columns=columns)

# Display the DataFrame
print(df)
