# -*- coding: utf-8 -*-
"""Pandas_Spreadsheets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14WRpDHJQGsftxwldKF9bDzOLQU1IKyPd

# **Comparison with spreadsheets**
"""

import pandas as pd
import numpy as np

url = (
    "https://raw.githubusercontent.com/pandas-dev"
    "/pandas/main/pandas/tests/io/data/csv/tips.csv"
)
tips = pd.read_csv(url)
tips.head()

tips = pd.read_csv(url)
tips.head()

# alternatively, read_table is an alias to read_csv with tab delimiter
# tips = pd.read_table("tips.csv", header=None)

tips.to_excel("/content/drive/MyDrive/data_practices/pandas/data/tips.xlsx")

# Read the Excel file
tips_df = pd.read_excel("/content/drive/MyDrive/data_practices/pandas/data/tips.xlsx")

# Display the first few rows of the DataFrame
print(tips_df.head())

tips["total_bill"] = tips["total_bill"] - 2

tips

tips["new_bill"] = tips["total_bill"] / 2
tips

tips = tips.drop("new_bill", axis=1)

tips[tips["total_bill"] > 10]

is_dinner = tips["time"] == "Dinner"
is_dinner

tips["bucket"] = np.where(tips["total_bill"] < 10, "low", "high")
tips

tips[["sex", "total_bill", "tip"]]

tips["date1"] = pd.Timestamp("2013-01-15")

tips["date2"] = pd.Timestamp("2015-02-15")

tips["date1_year"] = tips["date1"].dt.year

tips["date2_month"] = tips["date2"].dt.month

tips["months_between"] = tips["date2"].dt.to_period("M") - tips["date1"].dt.to_period(
    "M"
)


tips[["date1", "date2", "date1_year", "date2_month", "months_between"]]

tips.rename(columns={"total_bill": "total_bill_2"})

tips = tips.sort_values(["sex", "total_bill"])
tips.head(10)

tips["time"].str.len()

tips["sex"].str.find("ale")

tips["sex"].str[0:1]

firstlast = pd.DataFrame({"String": ["John Smith", "Jane Cook"]})

firstlast["First_Name"] = firstlast["String"].str.split(" ")[0]

firstlast["Last_Name"] = firstlast["String"].str.rsplit(" ")[1]

firstlast

df = pd.DataFrame({"AAA": [1] * 8, "BBB": list(range(0, 8))})
df

df = pd.DataFrame({"AAA": [1] * 8, "BBB": np.random.rand(8)})
df

df = pd.DataFrame({"AAA": [1] * 8, "BBB": np.random.randint(80, size=8)})
df

series = list(range(1, 5))
series

df.loc[2:5, "AAA"] = series
df

df = pd.DataFrame(
    {
        "class": ["A", "A", "A", "B", "C", "D"],
        "student_count": [42, 35, 42, 50, 47, 45],
        "all_pass": ["Yes", "Yes", "Yes", "No", "No", "Yes"],
    }
)

df

df.drop_duplicates()

pd.pivot_table(tips, values="tip", index=["size"], columns=["sex"], aggfunc=np.average)

tips

tips == "sun"

tips["day"].str.contains("S")

tips.replace("Thu", "Thursday")
