# -*- coding: utf-8 -*-
"""pandas_intermediate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fvheiggiT7IGV1M99yjJBXNSNixpdeWq

# **create plots in pandas**
"""

from google.colab import drive

drive.mount("/content/drive")

"""# WORKING ON AIR QUALITY DATA"""

import pandas as pd
import matplotlib.pyplot as plt

"""**parse_dates=True, helps to plot the dates properly**"""

data = pd.read_csv(
    "/content/drive/MyDrive/data_practices/pandas/data/air_quality_no2.csv",
    index_col=0,
    parse_dates=True,
)
data.head()

data.plot()
plt.show()

paris = data["station_paris"].plot()
# plt.show()

"""**alpha is use for opacity of points in graph** bold text"""

data.plot.scatter(x="station_london", y="station_paris", alpha=0.5).plot()

data.plot.box()

"""**subplots is use for multiple plots of columns**"""

areas = data.plot.area(figsize=(12, 8), subplots=True)
# areas

data.plot.line(y="station_london")

fig, axs = plt.subplots(figsize=(12, 4))  # Create an empty Matplotlib Figure and Axes
data.plot.area(ax=axs)  # Use pandas to put the area plot on the prepared Figure/Axes
axs.set_ylabel("concentration")  # Do any Matplotlib customization you like
fig.savefig(
    "concentrations.png"
)  # Save the Figure/Axes using the existing Matplotlib method.
plt.show()  # Display the plot
