# -*- coding: utf-8 -*-
"""pandas_intro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10F2Rd62vra3uK4HtJepDtnq4pYqJh-tp
"""

import pandas as pd

df = pd.DataFrame(
    {
        "Name": [
            "Rahul",
            "Anil",
            "Mahesh",
            "Ravi",
        ],
        "College": ["uvpce", "skpcer", "bsp", "vpce"],
        "Age": [18, 19, 21, 20],
    }
)

df

df["Name"]

location = pd.Series(["ahmedabad", "gandhinagar", "amreli", "surat"], name="Address")

location

df["Age"].max()

df.describe()

dt = pd.read_csv("titanic.csv")

dt

dt.describe()

dt.head()

dt.tail(8)

dt.dtypes

dt.to_excel("new.xlsx", sheet_name="titanic_spreadsheet", index=False)

excel = pd.read_excel("titanic.xlsx")
excel

print(excel["Age"].max())

dt.info()

base_info = dt[["Name", "Sex", "Age"]]
base_info

base_info.max()

base_info["Name"].shape

type(dt["Age"])

base_info.head()

dt[["Age", "Sex"]].shape

dt

# male = dt["Sex"]=="male"
male = dt[dt["Sex"] == "male"]
male

age_lessthan_50 = dt[dt["Age"] < 50]
age_lessthan_50

age_lessthan_50.shape
